#+TITLE: How to setup a multi-master k8s cluster using vagrant
#+AUTHOR: shizhz
#+STARTUP: overview

* Issues
** Private Network中IP范围的问题
#+begin_quote
Problem:

The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.

  Address: 10.10.10.200
  Ranges: 192.168.56.0/21

Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:

  https://www.virtualbox.org/manual/ch06.html#network_hostonly

#+end_quote

解决方法：
打开或者新建文件 ~/etc/vbox/networks.conf~, 并填入如下内容：
#+begin_quote
 * 10.0.0.0/8 192.168.0.0/16
 * 2001::/64
#+end_quote

参考：https://stackoverflow.com/a/70704094/1000254
** ETCD集群的参数配置问题
问题描述：
采用Stack-ETCD的模式时，通过kubeadm join加入的额外control plane节点的etcd无法成功加入集群。

原因：
默认情况下kubeadm join命令没有传递参数 ~--apiserver-advertise-address=$ADVERTISE_IP~, 导致etcd在启动时使用默认网卡的IP作为peer ip加入集群，默认使用的网络设备为 ~eth0~, 在vagrant启动的虚拟机中，该网卡是nat设备，每台机器的该网卡的IP都是一样的，因此导致额外的ETCD节点无法加入集群中。

解决办法：
每台control plane节点加入时，通过 ~--apiserver-advertise-address=$ADVERTISE_IP~ 将本机的public IP或者private IP传递进去。见 [[file:scripts/master.sh][master.sh]] 脚本。
